    - name: Filter proxies that open Telegram
      run: |
        python3 - << 'EOF'
        import requests

        good_proxies = []
        with open("sub.txt", "r", encoding="utf-8") as f:
            proxies = [line.strip() for line in f if line.strip()]

        for proxy in proxies:
            try:
                r = requests.get(
                    "https://web.telegram.org/k/",
                    proxies={"http": proxy, "https": proxy},
                    timeout=5
                )
                if r.status_code == 200:
                    good_proxies.append(proxy)
            except:
                continue

        with open("sub.txt", "w", encoding="utf-8") as f:
            f.write("\n".join(good_proxies))
        EOF
